version: '3.7'

services:
  commento:
    image: caroga/commentoplusplus:v1.8.6
    environment:
      COMMENTO_ORIGIN: 'http://172.28.28.28'
      COMMENTO_PORT: '8080'
      COMMENTO_POSTGRES: 'postgres://username:password@db:5432/commento?sslmode=disable'
      #COMMENTO_FORBID_NEW_OWNERS: 'true' # enable this after your own registration
      COMMENTO_GZIP_STATIC: 'true'
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    image: postgres:12.5-alpine
    environment:
      POSTGRES_DB: 'commento'
      POSTGRES_USER: 'ramtin'
      POSTGRES_PASSWORD: '123456'

